name: Upgrade docker hub image
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  upgrade-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and Push
        run: ./scripts/build-and-push.sh latest
