name: Update docker hub readme
on:
  push:
    branches:
      - 'main'
    paths:
      - 'README.md'
      - '.github/workflows/readme-updater.yaml'

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: anderpuqing/mindustry
